// ─── YaYa Chicken · seed данные (копия из data.js) ─────────────────────
// Используются только при пустых таблицах (см. initDb в server.js).

const DEFAULT_STOCK = [
  {id:'r1',  name:'Куриное мясо (крылышки)',      qty:20,  unit:'кг',   min:5,    max:20,  location:'workshop'},
  {id:'r2',  name:'Куриное мясо (стрипсы)',       qty:15,  unit:'кг',   min:5,    max:15,  location:'workshop'},
  {id:'r3',  name:'Куриное мясо (котлета/донер)', qty:15,  unit:'кг',   min:5,    max:15,  location:'workshop'},
  {id:'r4',  name:'Говядина',                     qty:15,  unit:'кг',   min:5,    max:15,  location:'workshop'},
  {id:'r5',  name:'Жир говяжий (іш май)',         qty:5,   unit:'кг',   min:1,    max:5,   location:'workshop'},
  {id:'r6',  name:'Курдюк',                       qty:2,   unit:'кг',   min:0.5,  max:2,   location:'workshop'},
  {id:'r7',  name:'Айран',                        qty:10,  unit:'л',    min:3,    max:10,  location:'workshop'},
  {id:'r8',  name:'Майонез',                      qty:8,   unit:'кг',   min:2,    max:8,   location:'workshop'},
  {id:'r9',  name:'Лук репчатый',                 qty:5,   unit:'кг',   min:1,    max:5,   location:'workshop'},
  {id:'r10', name:'Чеснок',                       qty:2,   unit:'кг',   min:0.3,  max:2,   location:'workshop'},
  {id:'r11', name:'Томаты свежие',                qty:5,   unit:'кг',   min:1,    max:5,   location:'workshop'},
  {id:'r12', name:'Огурцы солёные',               qty:5,   unit:'кг',   min:1,    max:5,   location:'workshop'},
  {id:'r13', name:'Перец болгарский',             qty:2,   unit:'кг',   min:0.5,  max:2,   location:'workshop'},
  {id:'r14', name:'Петрушка',                     qty:0.5, unit:'кг',   min:0.1,  max:0.5, location:'workshop'},
  {id:'r15', name:'Общая приправа',               qty:3,   unit:'кг',   min:0.5,  max:3,   location:'workshop'},
  {id:'r16', name:'Соль обычная',                 qty:5,   unit:'кг',   min:1,    max:5,   location:'workshop'},
  {id:'r17', name:'Соль кристаллик',              qty:3,   unit:'кг',   min:0.5,  max:3,   location:'workshop'},
  {id:'r18', name:'Паприка',                      qty:1,   unit:'кг',   min:0.2,  max:1,   location:'workshop'},
  {id:'r19', name:'Перец чёрный молотый',         qty:0.5, unit:'кг',   min:0.1,  max:0.5, location:'workshop'},
  {id:'r20', name:'Перец красный',                qty:0.3, unit:'кг',   min:0.05, max:0.3, location:'workshop'},
  {id:'r21', name:'Приправа шашлычная',           qty:1,   unit:'кг',   min:0.2,  max:1,   location:'workshop'},
  {id:'r22', name:'Уксус 70%',                    qty:0.3, unit:'л',    min:0.05, max:0.3, location:'workshop'},
  {id:'r23', name:'Горчичный соус',               qty:5,   unit:'л',    min:1,    max:5,   location:'workshop'},
  {id:'r24', name:'Томатный соус',                qty:5,   unit:'л',    min:1,    max:5,   location:'workshop'},
  {id:'r25', name:'Масло растительное',           qty:10,  unit:'л',    min:3,    max:10,  location:'workshop'},
  {id:'r26', name:'Хлеб для котлет',              qty:5,   unit:'кг',   min:1,    max:5,   location:'workshop'},
  {id:'r30', name:'Мука пшеничная',               qty:10,  unit:'кг',   min:3,    max:10,  location:'workshop'},
  {id:'r32', name:'Яйцо',                         qty:60,  unit:'шт.',  min:20,   max:60,  location:'workshop'},
  {id:'r27', name:'Булка для бургера',            qty:50,  unit:'шт.',  min:15,   max:50,  location:'kitchen'},
  {id:'r28', name:'Лаваш / тортилья',             qty:40,  unit:'шт.',  min:10,   max:40,  location:'kitchen'},
  {id:'r29', name:'Тесто для пиццы',              qty:10,  unit:'шт.',  min:3,    max:10,  location:'kitchen'},
  {id:'r31', name:'Картофель фри',                qty:30,  unit:'кг',   min:8,    max:30,  location:'kitchen'},
  {id:'r33', name:'Творог',                       qty:3,   unit:'кг',   min:0.5,  max:3,   location:'kitchen'},
  {id:'r34', name:'Coca Cola',                    qty:48,  unit:'бут.', min:12,   max:48,  location:'kitchen'},
  {id:'r35', name:'Сыр',                          qty:5,   unit:'кг',   min:1,    max:5,   location:'kitchen'},
  {id:'r36', name:'Наггетсы (заготовка)',         qty:5,   unit:'кг',   min:1,    max:5,   location:'kitchen'},
  {id:'r37', name:'Масло сливочное',              qty:1,   unit:'кг',   min:0.2,  max:1,   location:'kitchen'},
];

const DEFAULT_WS_STOCK = [
  {id:'p1',  name:'Крылышки маринованные (гот.)', qty:100, unit:'шт.', min:20},
  {id:'p2',  name:'Стрипсы маринованные (гот.)',  qty:80,  unit:'шт.', min:20},
  {id:'p3',  name:'Котлета куриная (гот.)',        qty:50,  unit:'шт.', min:10},
  {id:'p4',  name:'Котлета говяжья (гот.)',        qty:50,  unit:'шт.', min:10},
  {id:'p5',  name:'Шампур куриный (гот.)',          qty:5,   unit:'кг',  min:1},
  {id:'p6',  name:'Шампур говяжий (гот.)',          qty:5,   unit:'кг',  min:1},
  {id:'p7',  name:'Донер соус (гот.)',             qty:5,   unit:'л',   min:1},
  {id:'p8',  name:'Бургер красный соус (гот.)',    qty:3,   unit:'л',   min:0.5},
  {id:'p9',  name:'Бургер белый соус (гот.)',      qty:3,   unit:'л',   min:0.5},
  {id:'p10', name:'Тесто для блинов (гот.)',       qty:5,   unit:'кг',  min:1},
];

const DEFAULT_WS_RECIPES = [
  {id:'wr1', name:'Крылышки маринованные',
   items:[
     {ingId:'r1',  qty:0.05,  unit:'кг'},
     {ingId:'r15', qty:0.012, unit:'кг'},
     {ingId:'r16', qty:0.003, unit:'кг'},
   ], outputId:'p1', outputQty:1, outputUnit:'шт.'},
  {id:'wr2', name:'Стрипсы маринованные',
   items:[
     {ingId:'r2',  qty:0.07,  unit:'кг'},
     {ingId:'r15', qty:0.011, unit:'кг'},
     {ingId:'r16', qty:0.004, unit:'кг'},
     {ingId:'r7',  qty:0.05,  unit:'л'},
   ], outputId:'p2', outputQty:1, outputUnit:'шт.'},
  {id:'wr3', name:'Котлета куриная',
   items:[
     {ingId:'r3',  qty:0.113, unit:'кг'},
     {ingId:'r9',  qty:0.031, unit:'кг'},
     {ingId:'r26', qty:0.025, unit:'кг'},
     {ingId:'r16', qty:0.0015,unit:'кг'},
   ], outputId:'p3', outputQty:1, outputUnit:'шт.'},
  {id:'wr4', name:'Котлета говяжья',
   items:[
     {ingId:'r4',  qty:0.07,  unit:'кг'},
     {ingId:'r9',  qty:0.015, unit:'кг'},
     {ingId:'r26', qty:0.012, unit:'кг'},
     {ingId:'r5',  qty:0.011, unit:'кг'},
     {ingId:'r16', qty:0.001, unit:'кг'},
     {ingId:'r19', qty:0.00025,unit:'кг'},
     {ingId:'r17', qty:0.00025,unit:'кг'},
   ], outputId:'p4', outputQty:1, outputUnit:'шт.'},
  {id:'wr5', name:'Шампур куриный',
   items:[
     {ingId:'r3',  qty:1.0,   unit:'кг'},
     {ingId:'r7',  qty:0.03,  unit:'л'},
     {ingId:'r16', qty:0.004, unit:'кг'},
     {ingId:'r8',  qty:0.02,  unit:'кг'},
     {ingId:'r17', qty:0.0065,unit:'кг'},
     {ingId:'r21', qty:0.0075,unit:'кг'},
     {ingId:'r15', qty:0.0075,unit:'кг'},
     {ingId:'r25', qty:0.015, unit:'л'},
   ], outputId:'p5', outputQty:1, outputUnit:'кг'},
  {id:'wr6', name:'Шампур говяжий',
   items:[
     {ingId:'r4',  qty:0.7,   unit:'кг'},
     {ingId:'r5',  qty:0.2,   unit:'кг'},
     {ingId:'r3',  qty:0.1,   unit:'кг'},
     {ingId:'r6',  qty:0.025, unit:'кг'},
     {ingId:'r15', qty:0.007, unit:'кг'},
     {ingId:'r16', qty:0.0065,unit:'кг'},
     {ingId:'r17', qty:0.0065,unit:'кг'},
     {ingId:'r10', qty:0.01,  unit:'кг'},
     {ingId:'r13', qty:0.02,  unit:'кг'},
     {ingId:'r9',  qty:0.015, unit:'кг'},
     {ingId:'r32', qty:0.2,   unit:'шт.'},
   ], outputId:'p6', outputQty:1, outputUnit:'кг'},
  {id:'wr7', name:'Донер соус',
   items:[
     {ingId:'r11', qty:0.3,   unit:'кг'},
     {ingId:'r14', qty:0.025, unit:'кг'},
     {ingId:'r10', qty:0.017, unit:'кг'},
     {ingId:'r12', qty:0.017, unit:'кг'},
     {ingId:'r16', qty:0.01,  unit:'кг'},
     {ingId:'r18', qty:0.009, unit:'кг'},
     {ingId:'r19', qty:0.004, unit:'кг'},
     {ingId:'r20', qty:0.0035,unit:'кг'},
     {ingId:'r22', qty:0.0004,unit:'л'},
     {ingId:'r17', qty:0.008, unit:'кг'},
   ], outputId:'p7', outputQty:1, outputUnit:'л'},
  {id:'wr8', name:'Бургер красный соус',
   items:[
     {ingId:'r23', qty:0.4,   unit:'л'},
     {ingId:'r24', qty:0.4,   unit:'л'},
     {ingId:'r8',  qty:0.05,  unit:'кг'},
     {ingId:'r25', qty:0.05,  unit:'л'},
   ], outputId:'p8', outputQty:1, outputUnit:'л'},
  {id:'wr9', name:'Бургер белый соус',
   items:[
     {ingId:'r8',  qty:0.6,   unit:'кг'},
     {ingId:'r12', qty:0.4,   unit:'кг'},
   ], outputId:'p9', outputQty:1, outputUnit:'л'},
  {id:'wr10', name:'Тесто для блинов',
   items:[
     {ingId:'r30', qty:0.5,   unit:'кг'},
     {ingId:'r32', qty:2,     unit:'шт.'},
     {ingId:'r25', qty:0.03,  unit:'л'},
     {ingId:'r16', qty:0.005, unit:'кг'},
   ], outputId:'p10', outputQty:1, outputUnit:'кг'},
];

// ─── Готовка кухни: «сырьё → готовые порции» (стадия 1) ───────────────
// id = menuId блюда; outputId = 'ready_'+id (строки pf_stock location='kitchen').
const DEFAULT_COOK_RECIPES = [
  { id:'s14', name:'Фри', emoji:'🍟',
    items:[
      { ingId:'r31', qty:0.2, unit:'кг' },
    ], outputId:'ready_s14', outputQty:1, outputUnit:'шт.' },
];

const DEFAULT_TECH_CARDS = {
  'w6':  [{ingId:'p1',qty:30,unit:'шт.'}],
  'w7':  [{ingId:'p1',qty:20,unit:'шт.'}],
  'w8':  [{ingId:'p1',qty:8, unit:'шт.'}],
  'w9':  [{ingId:'p2',qty:20,unit:'шт.'}],
  'w10': [{ingId:'p2',qty:14,unit:'шт.'}],
  'w11': [{ingId:'p2',qty:7, unit:'шт.'}],
  's12': [{ingId:'r36',qty:0.2,unit:'кг'}],
  's14': [{ingId:'ready_s14',qty:1,unit:'шт.'}],
  'b15': [{ingId:'p4',qty:1,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'p8',qty:0.03,unit:'л'},{ingId:'p9',qty:0.03,unit:'л'}],
  'b17': [{ingId:'p4',qty:1,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'r35',qty:0.02,unit:'кг'},{ingId:'p8',qty:0.03,unit:'л'},{ingId:'p9',qty:0.03,unit:'л'}],
  'b19': [{ingId:'p4',qty:2,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'p8',qty:0.04,unit:'л'},{ingId:'p9',qty:0.04,unit:'л'}],
  'b26': [{ingId:'p4',qty:1,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'r35',qty:0.02,unit:'кг'},{ingId:'ready_s14',qty:1,unit:'шт.'},{ingId:'r34',qty:1,unit:'бут.'}],
  'b16': [{ingId:'p3',qty:1,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'p8',qty:0.03,unit:'л'},{ingId:'p9',qty:0.03,unit:'л'}],
  'b18': [{ingId:'p3',qty:1,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'r35',qty:0.02,unit:'кг'},{ingId:'p8',qty:0.03,unit:'л'},{ingId:'p9',qty:0.03,unit:'л'}],
  'b20': [{ingId:'p3',qty:2,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'p8',qty:0.04,unit:'л'},{ingId:'p9',qty:0.04,unit:'л'}],
  'b27': [{ingId:'p3',qty:1,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'r35',qty:0.02,unit:'кг'},{ingId:'ready_s14',qty:1,unit:'шт.'},{ingId:'r34',qty:1,unit:'бут.'}],
  'b30': [{ingId:'p4',qty:1,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'p1',qty:8,unit:'шт.'},{ingId:'ready_s14',qty:1,unit:'шт.'},{ingId:'r34',qty:1,unit:'бут.'}],
  'b31': [{ingId:'p3',qty:1,unit:'шт.'},{ingId:'r27',qty:1,unit:'шт.'},{ingId:'p1',qty:8,unit:'шт.'},{ingId:'ready_s14',qty:1,unit:'шт.'},{ingId:'r34',qty:1,unit:'бут.'}],
  'd32': [{ingId:'p5',qty:0.2,unit:'кг'},{ingId:'r28',qty:1,unit:'шт.'},{ingId:'p7',qty:0.05,unit:'л'}],
  'd35': [{ingId:'p5',qty:0.2,unit:'кг'},{ingId:'r28',qty:1,unit:'шт.'},{ingId:'p7',qty:0.05,unit:'л'}],
  'd39': [{ingId:'p5',qty:0.2,unit:'кг'},{ingId:'r28',qty:1,unit:'шт.'},{ingId:'p7',qty:0.05,unit:'л'},{ingId:'ready_s14',qty:1,unit:'шт.'},{ingId:'r34',qty:1,unit:'бут.'}],
  'd33': [{ingId:'p6',qty:0.2,unit:'кг'},{ingId:'r28',qty:1,unit:'шт.'},{ingId:'p7',qty:0.05,unit:'л'}],
  'd36': [{ingId:'p6',qty:0.2,unit:'кг'},{ingId:'r28',qty:1,unit:'шт.'},{ingId:'p7',qty:0.05,unit:'л'}],
  'd38': [{ingId:'p6',qty:0.2,unit:'кг'},{ingId:'r28',qty:1,unit:'шт.'},{ingId:'p7',qty:0.05,unit:'л'},{ingId:'ready_s14',qty:1,unit:'шт.'},{ingId:'r34',qty:1,unit:'бут.'}],
  'd34': [{ingId:'p5',qty:0.1,unit:'кг'},{ingId:'p6',qty:0.1,unit:'кг'},{ingId:'r28',qty:1,unit:'шт.'},{ingId:'p7',qty:0.05,unit:'л'}],
  'p54': [{ingId:'r29',qty:1,unit:'шт.'},{ingId:'r24',qty:0.08,unit:'л'},{ingId:'r35',qty:0.1,unit:'кг'}],
  'p53': [{ingId:'r29',qty:1,unit:'шт.'},{ingId:'r24',qty:0.08,unit:'л'},{ingId:'r35',qty:0.08,unit:'кг'}],
  'p48': [{ingId:'r29',qty:1,unit:'шт.'},{ingId:'r35',qty:0.15,unit:'кг'}],
  'p46': [{ingId:'r29',qty:1,unit:'шт.'},{ingId:'r35',qty:0.1,unit:'кг'},{ingId:'r24',qty:0.08,unit:'л'}],
  'p47': [{ingId:'r29',qty:1,unit:'шт.'},{ingId:'r35',qty:0.1,unit:'кг'},{ingId:'r24',qty:0.08,unit:'л'}],
  'p51': [{ingId:'r29',qty:1,unit:'шт.'},{ingId:'r35',qty:0.15,unit:'кг'}],
  'b60': [{ingId:'p10',qty:0.1,unit:'кг'},{ingId:'r33',qty:0.05,unit:'кг'}],
  'b61': [{ingId:'p10',qty:0.1,unit:'кг'}],
  'b62': [{ingId:'p10',qty:0.1,unit:'кг'}],
  'b63': [{ingId:'p10',qty:0.1,unit:'кг'}],
  'b68': [{ingId:'p10',qty:0.1,unit:'кг'},{ingId:'r37',qty:0.01,unit:'кг'}],
  'b72': [{ingId:'p10',qty:0.1,unit:'кг'},{ingId:'p6',qty:0.08,unit:'кг'}],
  'b73': [{ingId:'p10',qty:0.1,unit:'кг'},{ingId:'p5',qty:0.08,unit:'кг'}],
  's1': [{ingId:'p1',qty:20,unit:'шт.'},{ingId:'p2',qty:30,unit:'шт.'},{ingId:'ready_s14',qty:4,unit:'шт.'},{ingId:'r34',qty:2,unit:'бут.'}],
  's2': [{ingId:'p1',qty:30,unit:'шт.'}],
  's4': [{ingId:'p1',qty:30,unit:'шт.'},{ingId:'ready_s14',qty:4,unit:'шт.'},{ingId:'r34',qty:2,unit:'бут.'},{ingId:'p7',qty:0.1,unit:'л'}],
  's5': [{ingId:'r36',qty:0.2,unit:'кг'},{ingId:'ready_s14',qty:0.75,unit:'шт.'},{ingId:'p1',qty:2,unit:'шт.'}],
};

module.exports = { DEFAULT_STOCK, DEFAULT_WS_STOCK, DEFAULT_WS_RECIPES, DEFAULT_COOK_RECIPES, DEFAULT_TECH_CARDS };
